use_frameworks!

target 'TFFoundation_Example' do
  pod 'TFFoundation', :path => '../'

  target 'TFFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
